language: scala

scala:
  - 2.11.11
  - 2.10.6

sudo: false

jdk:
  - oraclejdk7

matrix:
  include:
    - scala: 2.12.3
      jdk: oraclejdk8
    - scala: 2.13.0-M2
      jdk: oraclejdk8
    - scala: 2.11.11
      jdk: oraclejdk8
      sudo: required
      dist: trusty
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.0/bin/travis_setup.sh | bash -x
      script:
      - sbt ++$TRAVIS_SCALA_VERSION "applybuilderNative/test:run" $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

script:
  - sbt ++${TRAVIS_SCALA_VERSION} update compile test:compile applybuilderJS/test:run applybuilderJVM/test:run $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

env:
  global:
  - secure: m+G2B45N18wP4awXIDPk7UvvN0zMRYKkzrK3/Lg8fQxe4Iu44CeSieuFbUVs/xrJuGyBAPcnwYkHETf9teDgv2VkHOJxC3wuHJN1JRCYh+P2d/E1Z/ve4oEA7ykAtmAahfbbmT8J9Dlftjj/RRK4HESpWb51IXRelyO+Vv5CkdEcRjNI6Sy8MLqbRDG2NHZ7bBOohItxmASsQi0slIo6Qksoe3Hx0TN90gN07dvYmVrb8jyO9kdDmhzyp2gDr/GZfkfpTlKehW+YELE2Az9iqImeu+amZz+X9PwBVtVMoLlD7zhJ24eoioTDq46gK7f+cHTdfmYIRf6zuA4p7MMPniaGrR2g5dR1yg6bEqTsNVzswwYuVO2Cyfsom98jHslirY1LN8Lr7GK5dU71w21Y/msBvBnW6pgB4TG0GYm6prOjgMk/lZ/ZBKbyM7+3NKMdOvpSya4XE4kOqIvZ+rKo6uTWGE1AmB0uBmWVAb8NRSnYsKBujNAjs4sQwrbQz/LVSlQVH5ql4KM+LlZlDj+dyVP++HbJguC4PGxXKy8smX9jDPJ4SjY3/dJqb17+LppoLCbYyK+LtPJtxXIxs/D04x+vnbIa809lHDJ4N/d+Yg02KuRa9XygEakBONIwragN0oz4hHwCxbPkFt9yHVe1SZPpmEIFkXlyGAjkAo614Js=
  - secure: Cz9lVu9eD10Bbq9rPsUgkAS20Yxs/+DtV7YpKbiYo0F5ButVy1GAQWGRnX4IcpQG3d2l2/hQBrQ+9iNRFiFn9dH8cmxcEGCL8scxOdCDI9EQdDmdENPNz82Z8zOrx+V3JFlkmF6cjBbnd0XdegaVxMsL4EhpBpEW3CYrninirMSRgtATrTNgvMSk/roXYZ2MmFy574KcmPreGYSWt0ecfEB4EBX01R44HAe9CLI5lYtdjaNdgACqhVcy4YCWJVABfRYu/VFjmnMAODcaNU8lMUJZxALATIvTqy35SB9io45zFzz3OkIj22rJsr4Zjrv06JbuKEL6Nz4R0iUHeWWUuUFvmNWCGLA3rHJXJfsxl2ZgM10d2OywQOSy+xiCE5otVlzGB0KIqZ7w8nnqOjW78Bo/B4j3qCaRjhdh6D6jKY0/7pg3D4VugeG1iHYJxlCVz9XMT86QAsMMEQia1qjPskl4C4HIe7Sd366/oBF0I0ZjmGwN7oWX6FoE5YxQTB97f6jvFMlWJBdk2LSIyLPYXSLRCtIJQ4Yd/TN1xgA4cWJGKRkTwyjJd0if6tu0ncxE7ZKEwwSbfs3hlVvg8jRk8qyUsQcRCd9fdirIwV5uro5/mEbdu+2Vhs2J9Ewc1S5Sq9m0lssCULkuH8Fw75fCTqrsJ6lu3CSdzFk9JylCBso=
